/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stm32f4xx.h>

/*Function Propotype*/
void HSI_Sysclk(void); //función que permite seleccionar el HSI (reloj interno) como fuente para el SYSCLK

void HSE_Sysclk(void); //función que permite seleccionar el HSE (reloj externo)como fuente para el SYSCLK

int main(void)
{

	HSI_Sysclk(); //seleccionar HSI como fuente de reloj
	HSE_Sysclk();
    /* Loop forever */
	for(;;);
}

/*Function definition*/
void HSI_Sysclk(void){
	//1er paso: Habilitar el reloj requerido y esperar a que este listo:
	RCC -> CR |= RCC_CR_HSION;//habilitar el HSI:   RCC -> CR |= (1U << 0);
	while(!(RCC -> CR & RCC_CR_HSIRDY)); //Esperar a que el reloj se estabilice
	RCC->CFGR &= ~(RCC_CFGR_SW); //Seleccionar HSI como fuente de reloj del SYSCLK
	while(!(RCC->CFGR & RCC_CFGR_SWS)); //Esperar a que se habilite el HSI (revisa el estado del reloj)

	SystemCoreClockUpdate(); //actualiza la frecuencia que se ha definido para HSI (16 MHz)

}
void HSE_Sysclk(void){
	RCC -> CR |= RCC_CR_HSEON; //habilitar el HSE
	while(!(RCC->CR & RCC_CR_HSERDY));//Esperar a que el reloj se estabilice

	//Habilitar el modo ByPass para la fuente de reloj externo del STLINK
	RCC-> CFGR = RCC_CFGR_SW_HSE;  //Seleccionar HSE como fuente de sistema (SYSCLK)
	while(!(RCC->CFGR & RCC_CFGR_SWS_HSE)); //Esperar hasta que se haga el cambio de fuente de reloj
	SystemCoreClockUpdate(); //actualiza la frecuencia que se ha definido para HSE (8 MHz)



}
