/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stm32f4xx.h>
#include "defines_pines.h"
#include "delay.h"

#define TMR3_CH2	B,5


uint32_t capture[2];

void TMR3_Compare_PWMmode(void);

void GPIO_Init(void);


int main(void)
{
	GPIO_Init();
	TMR3_Compare_PWMmode();
    /* Loop forever */
	for(;;){
		TIM3->CCR2 = 1000;

	}
}


void TMR3_Compare_PWMmode(void){
	//configurar el pin asignado al canal 1
	RCC->AHB1ENR |= GPIOX_CLOCK(TMR3_CH2); //habilitando reloj
	GPIOX_MODER(MODE_ALTER,TMR3_CH2);  //configurando PA5 modo funcion alternativa
	GPIOX_AFR(2,TMR3_CH2);	//configurando funcion alternativa AF02, trabaja con tmr3
	GPIOX_OSPEEDR(MODE_SPD_VHIGH,TMR3_CH2); //configurando la velocidad del pin PA5 alta velocidad

	//configurar el timer
	/*
	 * F = CK_PSC /(PSC + 1)(ARR + 1)
	 * para F = 50 hz, CK_PSC = 16Mhz , Pres = 15
	 * ARR = (16E+6/(15 + 1)(50))-1
	 * ARR = 20000 - 1
	 * ARR = 19999 (valor aceptable 16bits)
	 */
	RCC->APB1ENR |= RCC_APB1ENR_TIM3EN; //habilitar el reloj del timer2
	TIM3->CR1 = 0; //configuracion del tmr2 ver datasheet
	TIM3->PSC = 16 - 1 ; //prescaler: 0 (0ff)
	TIM3->ARR = 20000 - 1; //limpiamos el valor de autorecarga

	//Configurar el modo de funcionamiento del canal
	TIM3->CCMR1 &=~TIM_CCMR1_CC1S; //configurar como salida Compare

	TIM3->CCMR1 &=~TIM_CCMR1_OC2M;
	TIM3->CCMR1 |= 0x6U<<12; //Compare modo PWM-> modo 1
	TIM3->CCER |= TIM_CCER_CC2E; //habilitamos el canal

	TIM3->CCR2 |= TIM_CR1_CEN; //habilitamos el TMR3

}

void GPIO_Init(void){
	RCC->AHB1ENR |= GPIOX_CLOCK(LED); //habilitando reloj para pin PA5 (led)
	GPIOX_MODER(MODE_OUT,LED); //PA5 salida
}

